// Web-only: the HTML shell Expo wraps around every statically-rendered page (web.output is
// "static" in app.json). This runs in Node at export time — no DOM, no browser APIs.
//
// Before this file existed Expo used its own default template; everything above the PWA block
// is that default, kept verbatim so the shell doesn't regress. The PWA additions are the
// manifest link, the iOS home-screen meta (iOS ignores manifest icons), and the service worker
// registration.
import { ScrollViewStyleReset } from 'expo-router/html'
import type { PropsWithChildren } from 'react'

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        {/* viewport-fit=cover is what makes env(safe-area-inset-*) report real values once the
            app is installed and running standalone behind a notch — react-native-safe-area-context
            (which ui/Screen.tsx relies on) reads exactly those on web, and without this they're
            all 0 and content sits under the status bar. */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover"
        />

        <link rel="manifest" href="/manifest.json" />
        {/* Matches ui/theme.ts's colors.background: the standalone status bar blends into the
            screen underneath instead of drawing a band of a different color. */}
        <meta name="theme-color" content="#F7F8FA" />
        <meta name="apple-mobile-web-app-title" content="Workouty" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />

        {/* Production only: sw.js is generated by workbox-cli from the exported dist (see
            workbox-config.js), so it doesn't exist under `expo start --web`. Registering it there
            would 404 — and worse, a service worker left over from serving a local `dist` on the
            same origin would then shadow the dev server with precached production assets. */}
        {process.env.NODE_ENV === 'production' && (
          <script dangerouslySetInnerHTML={{ __html: registerServiceWorker }} />
        )}

        {/*
          Disable body scrolling on web. This makes ScrollView components work closer to how they do on native.
          However, body scrolling is often nice to have for mobile web. If you want to enable it, remove this line.
        */}
        <ScrollViewStyleReset />
      </head>
      <body>{children}</body>
    </html>
  )
}

const registerServiceWorker = `
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('/sw.js').catch(function (error) {
      console.error('Service worker registration failed:', error)
    })
  })
}
`
